# Generated by Django 3.2.5 on 2021-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
