# Generated by Django 3.2.5 on 2021-08-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
