# Generated by Django 3.2.5 on 2021-08-05 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210805_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 8, 5)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='Time',
            field=models.TimeField(default=datetime.time(17, 0, 5, 964316)),
        ),
    ]
