# Generated by Django 3.2.5 on 2021-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210805_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
